# Generated by Django 3.0.8 on 2020-08-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooked', '0002_meal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
