# Generated by Django 3.0.8 on 2020-08-03 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooked', '0003_auto_20200803_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchn',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='kitchen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooked.Kitchn'),
        ),
    ]
