# Generated by Django 3.0.8 on 2020-08-03 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooked', '0005_auto_20200803_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='kitchen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cooked.Kitchn'),
        ),
    ]
