# Generated by Django 3.0.8 on 2020-08-07 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooked', '0006_auto_20200803_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='kitchen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='cooked.Kitchn'),
        ),
    ]
