# Generated by Django 3.0.8 on 2020-08-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooked', '0009_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='name',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='user',
        ),
    ]
